# Generated by Django 3.2.9 on 2022-03-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gorozhane_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Афиша'},
        ),
    ]
